config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :users do
   	get 'users/:id', to: 'users#show', as:'user'
 	end
	root to: "home#index"
	resources :jobs, :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/job.rb
class Job < ApplicationRecord
	belongs_to :user
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ApplicationRecord
	#create user method for avg of ratings
	has_many :jobs
	has_attached_file :avatar, 
	styles: { medium: "300x300>", thumb: "100x100>" }, 
	default_url: "http://coverrme.com/public-uploads/profile-pics/unknown.jpg"

  validates_attachment_content_type :avatar, 
  content_type: /\Aimage\/.*\z/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  ratyrate_rater
  ratyrate_rateable "overall", "friendliness", "timing", "work_ethic"

  before_post_process :check_file_size
	def check_file_size
  	valid?
  	errors[:avatar_file_size].blank?
	end

  def sorting_rating()
   ((self.average("timing") ? self.average("timing").avg : 0 ) + (self.average("friendliness") ? self.average("friendliness").avg : 0) + (self.average("work_ethic") ? self.average("work_ethic").avg : 0)) / 3
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

 	def index
		@user = User.find_by(params[:id])
	end

	private

	def user_params
	    params.require(:user).permit(:fname, :lname, :email, :avatar, :id)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
		@user = current_user
		@users = User.all.sort_by { |r| r.sorting_rating() }.reverse.first(5)
end
	private

	def user_params
	    params.require(:user).permit(:fname, :lname, :email, :description, :avatar, :id)
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

	def index
		@jobs = Job.all.sort_by { |r| r.id }.reverse
	end

	def show
		@job = Job.find_by_id(params[:id])
		@user = @job.user_id
		@u = User.find_by_id(@user)
	end

	def create
		@job = Job.new(job_params)
		if @job.save
			redirect_to @job, notice: "Job successfully created" 
		else
			render :new
		end
	end

	def new
		@job = Job.new
	end

	def edit
		@job = Job.find_by_id(params[:id])
	end

	def update
		@job = Job.find_by_id(params[:id])
		if @job.update(job_params)
			redirect_to @job
		end
	end

	def destroy
		@job = Job.find_by_id(params[:id])
		@job.destroy
		redirect_to "/jobs", notice: "Job successfully deleted"
	end

	private

	def job_params
		params.require(:job).permit(:id, :user_id, :title, :cost, :description, :location, :category)
	end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


	private

	  def sign_up_params
	    params.require(:user).permit(:fname, :lname, :description, :email, :password, :password_confirmation, :avatar)
	  end

	  def account_update_params
	    params.require(:user).permit(:fname, :lname, :description, :email, :current_password, :avatar)
	  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def show
		@user = User.find_by_id(params[:id])
	end

	def edit
		@user = User.find_by_id(params[:id])
	end

	def update
		@user = User.find_by_id(params[:id])
		if @user.update(user_params)
			redirect_to @user
		end
	end

	private

	def user_params
	    params.require(:user).permit(:fname, :lname, :description, :email, :avatar, :id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_helper.rb
module JobHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="jumbotron">
  	<center>
    <img src="https://vectr.com/tmp/a2NP34A4QM/d6MUk2SRU.svg?width=650&height=150&select=d6MUk2SRUpage0" alt="">
    </center>
	</div>
	<div class="modal-container">
		<button id="modal-pop">Learn more...</button>
	  <div id="modal" class="hidden">
	  <div class="modal-wrapper">
	  <h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi enim, tempore accusantium nobis, aperiam, iure ducimus id nostrum earum excepturi incidunt provident atque ab amet aspernatur sit illum. Ut, assumenda!</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi enim, tempore accusantium nobis, aperiam, iure ducimus id nostrum earum excepturi incidunt provident atque ab amet aspernatur sit illum. Ut, assumenda! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi enim, tempore accusantium nobis, aperiam, iure ducimus id nostrum earum excepturi incidunt provident atque ab amet aspernatur sit illum. Ut assumenda?</p>
		<% if !current_user %>
			<a href="/users/sign_up"><button class="submitty">Start Now!</button></a>
		<% end %>
		</div>
	</div>
	<div class="user-container">
		<h1>Top Workers</h1>
				<% @users.each do |user| %>
					<div class="user-item">
						<a href="/users/<%= user.id %>"><img src="<%= user.avatar %>" alt=""> </a>
						<br>
						<br>
						<p><strong><%= user.fname %> <%= user.lname %></strong></p>
					</div>
				<% end %>
		</div>
</div>

<script src="/js/home.js"></script>

app/views/jobs/edit.html.erb
<div class="wrapper">
		<h2>Edit your job information</h2>
	<div class="form-group">
		<%= form_for @job do |f| %>
			<%= f.hidden_field :user_id, value: current_user.id %>
		  <br>
		 	<%= f.label :title %>
		 	<%= f.text_field :title %>
			<br>
			<br>
			<%= f.label :location %>
			<%= f.text_field :location %>
		  <br>
			<br>
		  <%= f.label :cost %>
		  <%= f.number_field :cost %>
		  <br>
			<br>
		  <%= f.label :description %>
		  <%= f.text_field :description %>
		  <br>
			<br>
		  <%= f.label :category %>
		  <%= f.select :category,["Select One", "Yard Work", "Surveys", "Carpentry", "Pluming", "Automotive", "I.T.", "Design/Art", "Electrical", "Moving", "Personal Shopper", "Babysitter", "Locksmith", "Other"] %>
		  <br>
			<br>
		  <%= f.submit "Submit", :class=> "submitty" %>
		<% end %>
	</div>
</div>

app/views/jobs/index.html.erb
	<div class="wrapper fit_inside">
		<table class="table">
	 <thead>
		 <% if current_user %>

	 		<%= link_to "Create A Job", new_job_path%>
	 		<% end %>

	 <tr>
		 <th>Job Info</th>
		 <th>Location</th>
		 <th>Price</th>
</tr>
</thead>
	<tbody>
			<% @jobs.each do |job| %>
				<tr>
				 	<td><a href="/jobs/<%= job.id %>"><%= job.title %></a></td>
					<td><%= job.location %></td>
				 	<td>$<%= job.cost %></td>
				</tr>
				 <% end %>
		</tbody>
	</table>
</div>

app/views/jobs/new.html.erb
	<br>
	<br>
	<br>
	<div class="wrapper">
		<div class="form-group">
			<h1> Job Form </h1>
			<%= form_for @job do |f| %>
				<%= f.hidden_field :user_id, value: current_user.id %>
			  <br>
			 	<%= f.label :title %>
			 	<%= f.text_field :title %>
				<br>
				<br>
				<%= f.label :location %>
				<%= f.text_field :location %>
			  <br>
				<br>
			  <%= f.label :cost %>
			  <%= f.number_field :cost %>
			  <br>
				<br>
			  <%= f.label :description %>
			  <%= f.text_field :description %>
			  <br>
				<br>
			  <%= f.label :category %>
			  <%= f.select :category, ["Select One", "Yard Work", "Surveys", "Carpentry", "Pluming", "Automotive", "I.T.", "Design/Art", "Electrical", "Moving", "Personal Shopper", "Babysitter", "Locksmith", "Other"] %>
				<br>
				<br>
			  <%= f.submit "Submit", :class => 'submitty' %>
			<% end %>
	    </div>
  </div>

app/views/jobs/show.html.erb
<div class="wrapper-job">
	<a href="/jobs">Back to Job Listing</a>
	<div class="job-user">
		<h5>Posted by:</h5>
		<h4><%= @u.fname %></h4>
		<h4><%= @u.lname %></h4>
		<img src="<%= @u.avatar %>" alt="" width="150px">
		<div class="job-btn">
			<% if current_user.id != @job.user_id %>
				<button class="submitty" id="accept">Accept</button>
			<% else %>
				<%= button_to "Close Job", @job, :class=> "submitty", method: :delete, data: {confirm: "Are you sure?"}%>
				<a href="/jobs/<%= @job.id %>/edit"><button class="submitty">Edit</button></a>
			<% end %>
		</div>
	</div>
	<br>
	<h2><%= @job.title %></h2>
	<br>
	<h3>Location: <%= @job.location %></h3>
	<br>
	<h4>Pay: $<%= @job.cost %></h4>
	<br>
	<h4>Description</h4>
	<p class="desc"><%= @job.description %></p>
	<br>
	<br>
	<br>
	<p>Tags: <strong><%= @job.category %></strong></p>
</div>
<script type="text/javascript" src="/js/jobs.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OddJob</title>
    <%= csrf_meta_tags %>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'ratyrate.js', "data-turbolinks-track": false %>
  </head>

  <body>
  	<div class="navbar">
			<%= link_to "Home", "/"%>
	  	<% if current_user %>
			  <a href="/users/<%= current_user.id %>">My Profile</a>
			  <%= link_to "Job Listings", "/jobs"%>
	  		<%= link_to "Log out", destroy_user_session_path, method: :delete%>
	  	<% else %>
		  	<%= link_to "Log In", new_user_session_path%>
		  	<%= link_to "Sign Up", new_user_registration_path%>
		  <% end %>
		</div>
    <%= yield %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/users/show.html.erb
<div class="profile">
	<div class="info">
		<h3><%= @user.fname %> <%= @user.lname %> </h3>
		<div class="pro-pic">
			<img src="<%= @user.avatar (:medium)%>" alt="">
		</div>
		<h4>E-mail: <%= @user.email %></h4>
	</div>
	<div class="profile-right">
		<div class="description">
			<h4>About me:</h4>
			<p><%= @user.description %></p>
		</div>
		<div class="rating">
			<span class="rating-display"><p>Friendliness:</p> <%= rating_for @user, "friendliness" %></span>
			<span class="rating-display"><p>Timing:</p><%= rating_for @user, "timing" %></span>
			<span class="rating-display"><p>Work Ethic:</p><%= rating_for @user, "work_ethic" %></span>
		</div>
		<br>
		<div class="edit-btn">
			<% if current_user %>
				<% if current_user.id === @user.id %>
					<%= link_to "Edit Profile", "/users/edit", :class => 'submitty'%>
				<% end %>
			<% end %>
		</div>
	</div>
</div>